defaults:
  actions:
    queue:
      name: default
      method: squash
      commit_message_template: |-
        {{ title }} (#{{ number }})
        {{ body }}
queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: automatic merge for master
    conditions:
      - base=master
      - -draft
      - label!=do-not-merge
      - or:
        - "#approved-reviews-by>=1"
        - and:
          - author=fallobst22
          - "body~=#ignore-review"
    actions:
      queue:
  - name: automatic approve for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - or:
        - label=minor
        - label=patch
        - label=maintenance
    actions:
      review:
  - name: assign pr
    conditions:
      - -draft
      - or:
        - -author=renovate[bot]
        - or:
          - "#check-failure>=1"
          - and:
            - -label=minor
            - -label=patch
            - -label=maintenance
    actions:
      assign:
        add_users:
          - fallobst22
      request_reviews:
        users:
          - fallobst22
